@startuml AddEvent

skinparam sequenceArrowThickness 2
skinparam roundcorner 10
skinparam DefaultFontSize 30
skinparam ArrowFontSize 24

title Add Event / Recurring Event

participant ":CommandParser" as CP
-> CP : parse("add event ...") or\n parse("add recurring ...")
activate CP
create "command:AddCommand" as AC
CP -> AC : new
activate AC
AC --> CP :
deactivate AC
CP -->[ : Command
deactivate CP

-> AC : execute(container)
activate AC
participant ":CategoryList" as CL
participant ":Category" as CAT
participant ":EventList" as EL
participant ":EventUI" as UI
participant ":Calendar" as CAL

alt Normal event
    note right of AC
        validation and parsing has been omitted from this sequence diagram
    end note
        AC -> CL : addEvent(categoryIndex, desc,\n from, to)
        activate CL

        CL -> CL : createEvent(categoryIndex, desc, \n from, to,false,-1)
        activate CL #grey
        CL --> CL : Event
        deactivate CL
        CL -> CAT : addEvent(Event)
        activate CAT
        CAT -> EL : add(Event)
        activate EL
        EL --> CAT
        deactivate EL
        CAT --> CL
        deactivate CAT
        CL --> AC

        AC -> CL : getLatestEvent()
        CL --> AC : Event
        deactivate CL

        AC -> CAL : registerTask(Event)
        activate CAL
        CAL --> AC
        deactivate CAL

        AC -> UI : printEventAdded(event,desc,totalEvents)
        activate UI
        UI --> AC : show added event
        AC -->[ : show added event
        deactivate UI

else Recurring Event

        AC -> CL : addRecurringWeeklyEvent(\n  eventCategoryIndex, desc, \n  from, to, calendar, \n  endDate, months)
        activate CL

        CL -> CL : increment recurringGroupId
        note right of CL
        recurringGroupId is incremented once
        and reused for all occurrences
        end note
        CL -> CL : createEvent(categoryIndex, desc, \n from, to,false,-1)
        activate CL #grey
        CL --> CL : Event
        deactivate CL


        CL -> CAT : addRecurringWeeklyEvent(event,\n  calendar, date, months)
        activate CAT

        CAT -> EL : addRecurringWeeklyEvent(event, \n calendar, date, months)
        activate EL

        EL -> EL : determine boundaryDateTime

        loop every 7 days until boundaryDateTime
            EL -> EL : create Event (same groupId)
            EL -> EL : add to tasks list
            EL -> CAL : registerTask(Event)
            activate CAL
            CAL --> EL
            deactivate CAL
        end

        EL --> CAT
        deactivate EL
        CAT --> CL
        deactivate CAT
        CL --> AC
        deactivate CL

        AC -> UI : printRecurringEventAdded(event)
        activate UI
        UI --> AC : show added recurring event
        deactivate UI
        AC -->[ : show added recurring event
        deactivate AC
    end

@enduml

