@startuml

actor User

participant ":UniTasker" as UniTasker
participant ":CommandParser" as CommandParser
participant ":CourseCommand" as CourseCommand
participant ":CourseParser" as CourseParser
participant ":CourseManager" as CourseManager
participant ":CourseStorage" as CourseStorage

User -> UniTasker : "course add <course_code>"
activate UniTasker

UniTasker -> CommandParser : parse(line)
activate CommandParser
CommandParser --> UniTasker : CourseCommand
deactivate CommandParser

UniTasker -> CourseCommand : execute(container)
activate CourseCommand

CourseCommand -> CourseParser : parse(courseCommand)
activate CourseParser

CourseParser -> CourseParser : handleAddCourse(args)

CourseParser -> CourseManager : addCourse(courseCode)
activate CourseManager

CourseManager -> CourseStorage : save(courseList)
activate CourseStorage
CourseStorage --> CourseManager :
deactivate CourseStorage

CourseManager --> CourseParser :
deactivate CourseManager

CourseParser --> CourseCommand :
deactivate CourseParser

CourseCommand --> UniTasker :
deactivate CourseCommand

UniTasker --> User :
deactivate UniTasker

@enduml