@startuml DateUtilsSequenceDiagram
!pragma teoz true


skinparam sequenceArrowThickness 2
skinparam roundcorner 10
skinparam DefaultFontSize 24
skinparam ArrowFontSize 24

title DateUtils: parse() Sequence Diagram

participant ":CommandParser" as CP

-> CP : add VarDate \n(e.g. "... 31-12-2025 1800")
activate CP

create "command:AddCommand" as command
CP -> command : new AddCommand(sentence)
activate command
command --> CP
deactivate command

<-- CP
deactivate CP
-> command : execute(container)

activate command
command -> command : handleAddDeadline / handleAddEvent(container)
activate command #grey
note over command : generalised — represents both in code

participant ":DateUtils" as DU
participant ":LocalDateTime" as LDT
note over CP, LDT : This sequence diagram covers the happy path only.

command -> DU : parseDateTime(input)
activate DU #white

DU -> DU : parse(input, isLoading=false)
activate DU #grey

alt input matches FULL_FORMATTER
    DU -> LDT : LocalDateTime.parse(trimmedInput, FULL_FORMATTER)
    activate LDT
    LDT --> DU : parsedDate
    deactivate LDT

else input matches DATE_ONLY_FORMATTER
    DU -> LDT : LocalDate.parse(trimmedInput, DATE_ONLY_FORMATTER)
    activate LDT
    LDT --> DU : date
    deactivate LDT
    DU -> LDT : date.atTime(23, 59)
    activate LDT
    LDT --> DU : parsedDate (time defaulted to 23:59)
    deactivate LDT
end

alt isLoading == false
    DU -> DU : validateNotPast(parsedDate, trimmedInput)
    activate DU #lightblue
    DU -->DU
    deactivate DU

else isLoading == true
    note over DU : skip validateNotPast()\n(loading from saved data)
end

DU -> DU : validateYearRange(parsedDate, trimmedInput)
note over DU : startYear = LocalDate.now().getYear()\nendYear = UniTasker.getEndYear()
activate DU #lightblue
||20||
deactivate DU
DU -->DU
DU --> DU
deactivate DU
DU --> command : parsedDate (LocalDateTime)

deactivate DU
command -->command
deactivate command
 <-- command : task scheduled and saved successfully
deactivate command
deactivate command

deactivate CP

@enduml