@startuml

actor User

participant ":UniTasker" as UniTasker
participant ":CommandParser" as CommandParser

User -> UniTasker : "delete marked"
activate UniTasker

UniTasker -> CommandParser : parse(line)
activate CommandParser

create "command:DeleteCommand" as command
CommandParser -> command : new
activate command
command --> CommandParser
deactivate command

CommandParser --> UniTasker :
deactivate CommandParser

UniTasker -> command : execute(container)
activate command

participant ":AppContainer" as AppContainer

command -> AppContainer : categories()
activate AppContainer
AppContainer --> command
deactivate AppContainer

participant "categories:CategoryList" as categories

command -> categories : deleteMarkedTasks()
activate categories

loop for each Category
    participant ":Category" as Category
    categories -> Category : deleteMarkedTasks()
    activate Category


    Category -> Category : todoList.deleteMarked()
    activate Category
    Category --> Category
    deactivate Category
    Category -> Category : deadlineList.deleteMarked()
    activate Category
    Category --> Category
    deactivate Category
    Category -> Category : eventList.deleteMarked()
    activate Category
    Category --> Category
    deactivate Category

    Category --> categories :
    deactivate Category
end

categories --> command :
deactivate categories

participant ":UI" as UI

command -> UI : printAllMarkedDeleted()
activate UI
UI --> command
deactivate UI

participant ":Storage" as Storage

command -> command : saveData()
activate command
command -> Storage : save(categories)
activate Storage
Storage --> command :
deactivate Storage
deactivate command

command -> AppContainer : calendar()
activate AppContainer
AppContainer --> command
deactivate AppContainer

participant ":Calendar" as Calendar

command -> Calendar : refreshCalendar(categories, calendar)
activate Calendar
Calendar --> command :
deactivate Calendar

command --> UniTasker :
deactivate command
destroy command

UniTasker --> User :
deactivate UniTasker

@enduml