@startuml DeleteEvent

skinparam sequenceArrowThickness 2
skinparam roundcorner 10
skinparam DefaultFontSize 28
skinparam ArrowFontSize 24

title List Event (Populating map for deletion (Main List))

actor User

participant ":UniTasker" as UT
participant ":CommandParser" as CP

User -> UT : list event
activate UT

UT -> CP : parse(line)
activate CP
create "command:ListCommand" as LC
CP -> LC : new
activate LC
LC --> CP
deactivate LC
CP --> UT : Command
deactivate CP

participant ":CategoryList" as CL
participant ":GeneralUI" as GU

UT -> LC : execute(container)
activate LC

LC -> CL : getAllEvents(showAll,showNormalEventsOnly)
activate CL
CL -> CL : build display string

note right of CL
Iterates through categories and events,
filters based on view,
and formats output
end note

CL -> CL : build activeDisplayMap

note right of CL
Maps UI index → EventReference
(categoryIndex, eventIndex)
end note

CL -> CL : set currentView
CL --> LC : String of formatted events
deactivate CL
LC -> GU : print list
activate GU
GU --> LC : show list
deactivate GU
LC --> UT : show list
deactivate LC
UT --> User: show list
deactivate UT
@enduml