@startuml

actor User

participant ":UniTasker" as UniTasker
participant ":CommandParser" as CommandParser

participant ":UI" as UI
participant ":Storage" as Storage
participant ":AppContainer" as AppContainer

User -> UniTasker : "reorder todo 1 1 2"
activate UniTasker

UniTasker -> CommandParser : parse(line)
activate CommandParser

create "command:ReorderCommand" as command
CommandParser -> command : create
activate command
command --> CommandParser
deactivate command

CommandParser --> UniTasker :
deactivate CommandParser

UniTasker -> command : execute(container)
activate command

command -> AppContainer : reorderTodo(...)
activate AppContainer
AppContainer --> command :
deactivate AppContainer

command -> command : saveData()
activate command
command -> Storage : save(categories)
activate Storage
Storage --> command :
deactivate Storage
deactivate command

command -> UI : printReordered(...)
activate UI
UI --> command
deactivate UI

command --> UniTasker :
deactivate command
destroy command

UniTasker --> User :
deactivate UniTasker

@enduml