@startuml

actor User

participant ":UniTasker" as UniTasker
participant ":Command" as Command
participant ":UI" as UI
participant ":Storage" as Storage
participant ":AppContainer" as AppContainer

User -> UniTasker : "reorder todo 1 1 2"
activate UniTasker

UniTasker -> Command : parse(line)
activate Command

Command -> Command : execute(line)

Command -> AppContainer : getCategories()
activate AppContainer
Command -> AppContainer : reorderTodo(0, 0, 1)
AppContainer --> Command :
deactivate AppContainer

Command -> Command : saveData()
Command -> Storage : save(categories)
activate Storage
Storage --> Command :
deactivate Storage

Command -> UI : printReordered(...)
activate UI
UI --> Command
deactivate UI

Command --> UniTasker :
deactivate Command

UniTasker --> User :
deactivate UniTasker

@enduml