@startuml


actor User

participant ":UniTasker" as UniTasker


participant ":CommandParser" as CommandParser

User -> UniTasker : "reorder todo 1 1 2"
activate UniTasker

UniTasker -> CommandParser : parse(line)
activate CommandParser

create "command:ReorderCommand" as command
CommandParser -> command : new
activate command
command --> CommandParser
deactivate command


CommandParser --> UniTasker :
deactivate CommandParser

UniTasker -> command : execute(container)
activate command

participant ":AppContainer" as AppContainer

command -> AppContainer : categories()
activate AppContainer
AppContainer --> command
deactivate AppContainer

participant "categories:CategoryList" as categories

command -> categories : reorderTodo(...)
activate categories

categories --> command :
deactivate categories

participant ":Storage" as Storage

command -> command : saveData()
activate command
command -> Storage : save(categories)
activate Storage
Storage --> command :
deactivate Storage
deactivate command

participant ":UI" as UI

command -> UI : printReordered(...)
activate UI
UI --> command
deactivate UI

command --> UniTasker :
deactivate command
destroy command

UniTasker --> User :
deactivate UniTasker

note over UI
UI represents any class within the UI package
(e.g. TaskUi, ErrorUi)
end note

@enduml